### ISSUE TITLE
Preview of env variables broken if default shell is not fish

### ISSUE THREAD

**Issue by edclement** [patrickf3139/fzf-fish-integration#10]
Had to:
```bash
chsh -s /usr/bin/fish
```
in order to get the env variable preview working (and logout/login). Otherwise FZF will use whatever shell is defined the `$SHELL` variable which in my case was bash. That causes an error since bash doesn't know anything about `__fzf_search_shell_variables.fish`

I didn't try it but I'm thinking just adding:
```bash
SHELL=(which fish)
```
...before the call to fzf might fix the issue.

EDIT: thanks for the plugin btw

**Comment by patrickf3139** [comment]
Hey Ed, thanks for filing the issue. I was actually supposed to cover this edge case (well, edge case for people whose default shell is fish) when I first wrote it but forgot. Let me fix that right now for you!

**Comment by patrickf3139** [comment]
@edclement Well, I think I fixed it! Can you try and let me know if it doesn't? Thanks again for filling an issue and for using my plugin 🙂
