### ISSUE TITLE
Key bindings not working in vi mode

### ISSUE THREAD

**Issue by prasant94** [patrickf3139/fzf-fish-integration#13]
I had to manually set up the key bindings with the `-M` flag. Maybe that's something that can be handled automatically?

**Comment by patrickf3139** [comment]
Ah yes that's an oversight on my part. I seem to have not accounted for VI mode. Let me fix that for you. Thank you for reporting this @prasant94 !

**Comment by patrickf3139** [comment]
Hi @prasant94 I believe I have fixed the issue. Could you test and let me know if I didn't, please? Thanks!

**Comment by prasant94** [comment]
It's fixed now. Thanks!
